# Generated by Django 5.2.17 on 2026-09-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="portrait",
            field=models.ImageField(blank=True, upload_to="testimonials/"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.URLField(blank=True),
        ),
    ]
