# Generated by Django 5.1.7 on 2025-04-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-completion_date']},
        ),
        migrations.AddField(
            model_name='project',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
