# Generated by Django 5.2.17 on 2026-09-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteVisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("image", models.ImageField(upload_to="site/")),
                ("alt", models.CharField(max_length=255)),
                ("credit", models.CharField(blank=True, max_length=500)),
                ("source_url", models.URLField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="detail",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="focus",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="product",
            name="image_alt",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("live", "Live"),
                    ("development", "In development"),
                    ("available", "Available"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="website_url",
            field=models.URLField(blank=True),
        ),
    ]
