# Generated by Django 5.2.17 on 2026-09-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_sitevisual_alter_product_options_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="products/"),
        ),
    ]
