# Generated by Django 5.2.17 on 2026-09-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="portrait",
            field=models.ImageField(blank=True, upload_to="team/"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="position",
            field=models.CharField(
                choices=[
                    ("lead_developer", "Lead Developer"),
                    ("security_specialist", "Security Specialist"),
                    ("ceo_founder", "CEO & Founder"),
                    ("cto", "CTO"),
                    ("marketing_officer", "Marketing Officer"),
                ],
                default="lead_developer",
                max_length=255,
            ),
        ),
    ]
