# Generated by Django 5.2.17 on 2026-09-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_socialloginattempt_socialidentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, upload_to="profiles/"),
        ),
    ]
