# Generated by Django 5.2.17 on 2026-09-26 08:28

import django.db.models.deletion
from django.db import migrations, models


def preserve_publication_dates(apps, schema_editor):
    Post = apps.get_model("blog", "BlogPost")
    Post.objects.filter(is_published=True).update(published_at=models.F("created_at"))


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(preserve_publication_dates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="blogpost",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="blog.category",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
    ]
