# Generated by Django 5.2.17 on 2026-09-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_published_at_alter_blogpost_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to="journal/"),
        ),
    ]
