# Generated by Django 5.2.17 on 2026-09-25 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=250)),
                ("answer", models.TextField(max_length=3000)),
            ],
            options={
                "verbose_name": "FAQ",
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("approach", "Our approach"),
                            ("values", "Company values"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(max_length=2000)),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        choices=[
                            ("home-hero", "Home / Galaxy hero"),
                            ("home-services", "Home / Services"),
                            ("home-products", "Home / Products"),
                            ("home-approach", "Home / Approach"),
                            ("sign-in", "Sign in"),
                            ("about", "About introduction"),
                            ("contact", "Contact introduction"),
                            ("cta", "Contact invitation"),
                        ],
                        unique=True,
                    ),
                ),
                ("eyebrow", models.CharField(max_length=180)),
                (
                    "title",
                    models.TextField(
                        help_text="Line breaks are preserved in display headings.",
                        max_length=300,
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=2000)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default="Perpetual Labs", max_length=120)),
                (
                    "location",
                    models.CharField(default="Kampala, Uganda", max_length=180),
                ),
                (
                    "founded",
                    models.CharField(
                        default="2020",
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{4}$", "Use a four-digit year."
                            )
                        ],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="+256 703 163 074",
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[+\\d ()-]+$", "Use a phone number."
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default="hello.perpetuallabs@gmail.com", max_length=254
                    ),
                ),
                (
                    "whatsapp",
                    models.URLField(
                        default="https://wa.me/256703163074",
                        validators=[
                            django.core.validators.URLValidator(schemes=["https"])
                        ],
                    ),
                ),
                ("introduction", models.TextField(max_length=2000)),
                ("mission", models.TextField(max_length=2000)),
                ("vision", models.TextField(max_length=2000)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Site settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="single_site_settings"
                    )
                ],
            },
        ),
    ]
